"""JNFC garden photographs: white aggregate islands, winding pavers and supported trees.

Garden dimensions and planting locations are photo-proportioned, not a survey.
All texture pixels and landscape geometry are authored here, not copied imagery.
"""
import bpy, bmesh, math, random

def inside(x,z,poly):
    hit=False
    for a,b in zip(poly,poly[1:]+poly[:1]):
        if (a[1]>z)!=(b[1]>z) and x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0]:hit=not hit
    return hit

def finish(g,color,kind):
    m=g.mat(color);bs=m.node_tree.nodes['Principled BSDF']
    # Generated byte images are sampled as sRGB; author sRGB pixel values rather
    # than applying the material's linear conversion twice.
    rgb=tuple(int(color.lstrip('#')[i:i+2],16)/255 for i in (0,2,4))
    rng=random.Random(915 if kind=='grass' else 921);n=256;pixels=[]
    grids={size:[[rng.random() for _ in range(size)] for _ in range(size)] for size in (4,16,48)}
    def noise(u,v,size):
        x=u*size;z=v*size;i=math.floor(x);j=math.floor(z);a=x-i;b=z-j;a=a*a*(3-2*a);b=b*b*(3-2*b);grid=grids[size]
        return (1-b)*((1-a)*grid[j%size][i%size]+a*grid[j%size][(i+1)%size])+b*((1-a)*grid[(j+1)%size][i%size]+a*grid[(j+1)%size][(i+1)%size])
    for j in range(n):
        for i in range(n):
            u=i/n;v=j/n
            t=.91+.12*(noise(u,v,4)-.5)+.13*(noise(u,v,16)-.5)+.10*(noise(u,v,48)-.5)+rng.uniform(-.045,.045)
            pixels.extend((rgb[0]*t,rgb[1]*t,rgb[2]*t,1))
    im=bpy.data.images.new('Courtyard_original_'+kind,width=n,height=n);im.pixels.foreach_set(pixels);im.pack()
    node=m.node_tree.nodes.new('ShaderNodeTexImage');node.image=im;m.node_tree.links.new(node.outputs['Color'],bs.inputs['Base Color']);bs.inputs['Roughness'].default_value=.96

def boulder(g,x,z,w,h,d,color,rng):
    bm=bmesh.new();bmesh.ops.create_icosphere(bm,subdivisions=3,radius=1);bm.verts.ensure_lookup_table();bm.verts.index_update()
    verts=[]
    for v in bm.verts:
        scale=rng.uniform(.91,1.11);a,b,c=v.co
        verts.append((x+a*w*.5*scale,h*.41+max(-.41,b*.5*scale)*h,z+c*d*.5*scale))
    faces=[tuple(v.index for v in face.verts) for face in bm.faces];bm.free()
    g.mesh('garden_weathered_boulder',verts,faces,color,smooth=True)

def paved_outline(route,width):
    left=[];right=[]
    for i,p in enumerate(route):
        a=route[max(0,i-1)];b=route[min(len(route)-1,i+1)]
        before=[p[k]-a[k] for k in (0,1)] if i else [b[k]-p[k] for k in (0,1)]
        after=[b[k]-p[k] for k in (0,1)] if i<len(route)-1 else before
        normals=[[-d[1]/math.hypot(*d),d[0]/math.hypot(*d)] for d in (before,after)]
        m=[sum(n[k] for n in normals) for k in (0,1)];length=math.hypot(*m);m=[v/length for v in m]
        scale=width/2/max(.4,sum(m[k]*normals[0][k] for k in (0,1)))
        left.append([p[k]+m[k]*scale for k in (0,1)]);right.append([p[k]-m[k]*scale for k in (0,1)])
    return left+list(reversed(right))

def edging(g,name,poly,y=.04,closed=True):
    pairs=list(zip(poly,poly[1:]+poly[:1])) if closed else list(zip(poly,poly[1:]))
    for a,b in pairs:
        length=math.dist(a,b);n=max(1,math.ceil(length/.42))
        for i in range(n):
            p=[a[k]+(b[k]-a[k])*i/n for k in (0,1)];q=[a[k]+(b[k]-a[k])*(i+.97)/n for k in (0,1)]
            g.segment(name,p,q,.15,.11,'#5c6665',base=y,record=False)

def pebbles(g,poly,rng,count=2200):
    xmin=min(p[0] for p in poly);xmax=max(p[0] for p in poly);zmin=min(p[1] for p in poly);zmax=max(p[1] for p in poly)
    groups=[([],[]) for _ in range(4)]
    for i in range(count):
        x=rng.uniform(xmin,xmax);z=rng.uniform(zmin,zmax)
        if not inside(x,z,poly):continue
        r=rng.uniform(.025,.065);y=.08+r*.35;verts,faces=groups[i%4];o=len(verts)
        verts.extend([(x-r,y,z),(x,y,z-r*.8),(x+r,y,z),(x,y,z+r*.8),(x,y+r*.7,z)])
        faces.extend([(o,o+1,o+4),(o+1,o+2,o+4),(o+2,o+3,o+4),(o+3,o,o+4)])
    for i,(verts,faces) in enumerate(groups):g.mesh('courtyard_white_aggregate_'+str(i),verts,faces,['#d9ddd9','#c4cbc7','#e5e4d9','#a6b1b0'][i])

def gravelbed(g,name,poly,rng):
    g.polygon('garden_gravel_'+name,poly,.045,.035,'#cdd4d0')
    pebbles(g,poly,rng);edging(g,'garden_dark_edge',poly)

def bush(g,x,z,size,rng):
    g.tube('garden_shrub_trunk',(x,.02,z),(x,.85*size,z),.035*size,'#62543e',n=8)
    for i in range(15):
        a=rng.random()*math.tau;r=math.sqrt(rng.random())*.52*size
        xx=x+math.cos(a)*r;zz=z+math.sin(a)*r;y=.65*size+rng.uniform(0,.38)*size
        if i%3==0:g.tube('garden_shrub_branch',(x,.38*size,z),(xx,y,zz),.014*size,'#665943',n=5)
        g.rock('garden_small_leaf_cluster',xx,y,zz,.5*size,.30*size,.42*size,rng.choice(['#4c6442','#68744a','#778151','#596e43']),rng)

def tree(g,x,z,size,rng,deciduous=False):
    h=(6.8 if deciduous else 2.9)*size
    base=(x,.03,z);fork=(x+.12,h*.46,z+.08)
    g.tube('garden_tree_trunk',base,fork,.13*size,'#746e59',n=10)
    for i in range(7 if deciduous else 5):
        a=i*math.tau/(7 if deciduous else 5)+rng.uniform(-.25,.25);r=(1.8 if deciduous else 1.2)*size
        joint=(x+math.cos(a)*r*.58,h*.76+rng.uniform(-.4,.3)*size,z+math.sin(a)*r*.58)
        end=(x+math.cos(a)*r,h+rng.uniform(-.5,.5)*size,z+math.sin(a)*r)
        g.tube('garden_tree_branch',fork,joint,.055*size,'#766d59',n=8);g.tube('garden_tree_branch',joint,end,.023*size,'#7d725d',n=6)
        for j in range(4):
            e=(end[0]+rng.uniform(-.7,.7)*size,end[1]+rng.uniform(-.1,.6)*size,end[2]+rng.uniform(-.7,.7)*size)
            g.tube('garden_tree_twig',joint,e,.009*size,'#7a6b54',n=5)
            if not deciduous or j==0:
                for k in range(4 if not deciduous else 2):
                    g.rock('garden_tree_foliage',e[0]+rng.uniform(-.3,.3)*size,e[1],e[2]+rng.uniform(-.3,.3)*size,.70*size,.26*size,.63*size,rng.choice(['#4b6246','#657348','#7d8051'] if not deciduous else ['#8e774f','#a48c58','#79674a']),rng)
    for i in range(3):
        a=i*math.tau/3;g.tube('garden_tree_support',(x+math.cos(a)*.65*size,.06,z+math.sin(a)*.65*size),(x,h*.50,z),.035*size,'#a29272',n=7)
    g.collider('garden_tree_collision',[[x-.2,z-.2],[x+.2,z-.2],[x+.2,z+.2],[x-.2,z+.2]],0,h)

def slab(g,x,z,w,d,angle,rng):
    points=[]
    for dx,dz in [(-.5,-.36),(-.35,-.5),(.43,-.5),(.5,-.30),(.5,.35),(.33,.5),(-.4,.5),(-.5,.24)]:
        xx=dx*w*rng.uniform(.92,1.08);zz=dz*d*rng.uniform(.92,1.08)
        points.append([x+xx*math.cos(angle)-zz*math.sin(angle),z+xx*math.sin(angle)+zz*math.cos(angle)])
    g.polygon('garden_irregular_stepping_slab',points,.017,.026,rng.choice(['#8a9493','#a3aaa7','#949c97']))

def courtyard(g):
    rng=random.Random(20260909)
    finish(g,'#939065','grass');finish(g,'#8a9493','granite');finish(g,'#b2afa1','paving')
    # The satellite shows a garden opening to the southwest, with another
    # property close to its eastern edge; this is not a rectangular public park.
    boundary=[[-12.3,-8.6],[12.8,-8.6],[12.0,9.5],[6.0,13.0],[6.0,36.0],[-16.0,39.0],[-17.0,23.0],[-12.8,15.0]]
    g.polygon('ground_floor_literature_garden',boundary,-.012,.018,'#939065')
    edging(g,'garden_perimeter_curb',boundary,y=-.03)
    # Continuous stone approach with a central route into the existing doorway.
    g.box('garden_path_bedding',0,.018,17.0,2.30,.035,15.7,'#7c8581',record=False)
    for row in range(31):
        for col in range(4):
            g.box('garden_main_paving',-.852+col*.568,.04,9.3+row*.495,.552,.028,.479,rng.choice(['#a0a8a2','#909994','#b2afa1','#a8aea7']),record=False)
    # Hexagonal white threshold stones observed directly in front of the entrance.
    for row in range(5):
        for col in range(8):
            x=-.97+col*.278+(row%2)*.139;z=8.12+row*.24
            pts=[[x+math.cos(i*math.tau/6)*.154,z+math.sin(i*math.tau/6)*.154] for i in range(6)]
            g.polygon('garden_hexagonal_threshold',pts,.026,.025,['#c4c4b6','#d2d0bd','#bdbfb3'][(row+col)%3])
    # Broad right rock island and the curved western tree island.
    east=[[1.8,11.1],[4.0,10.7],[5.6,12.0],[5.8,16.3],[5.4,19.4],[3.9,20.1],[2.2,18.9],[1.8,15.5]]
    west=[[-10.7,15.8],[-8.7,14.6],[-6.8,15.0],[-4.4,16.6],[-3.1,18.7],[-3.7,20.6],[-6.4,21.4],[-9.4,20.5],[-10.9,18.2]]
    gravelbed(g,'east',east,rng);gravelbed(g,'west',west,rng)
    for x,z,w,d,h in [(2.7,12.2,1.45,1.05,1.0),(4.5,14.1,1.8,1.3,1.4),(4.9,17.3,1.5,1.2,.9),(3.2,18.5,1.0,.85,.6),(-8.8,12.6,1.2,.95,1.1),(-4.7,15.2,1.1,.8,.7)]:
        boulder(g,x,z,w,h,d,rng.choice(['#676f67','#737970','#626c68']),rng)
        g.collider('garden_boulder_collision',[[x-w*.42,z-d*.42],[x+w*.42,z-d*.42],[x+w*.42,z+d*.42],[x-w*.42,z+d*.42]],0,h)
    # Larger rounded stones retain the raised rock bed, unlike a white ring of blocks.
    for i in range(30):
        t=i/29;x=1.8+t*4.0;z=15.8+math.sin(t*math.pi)*3.8
        g.rock('garden_cobble_retaining_edge',x,.16,z,.34,.33,.30,rng.choice(['#a1a59a','#898f83','#b3b6a6']),rng)
    # Two rows of winding stepping stones lead to the projecting west wing.
    for i in range(21):
        t=i/20;z=23.5-t*11.6;x=-1.6-3.0*math.sin(t*math.pi*.62)
        for side in (-1,1):slab(g,x+side*.46,z,.66,.45,-.25+t*.4,rng)
    for i in range(29):slab(g,-11.35,-7.9+i*.75,.74,.48,.05,rng)
    for i in range(28):slab(g,-10.8+i*.81,-7.8,.65,.47,.04,rng)
    for x,z,size in [(-7.8,17.6,.73),(-10.3,12.5,.78),(-3.0,13.0,.74)]:tree(g,x,z,size,rng)
    tree(g,4.5,16.1,1.0,rng,True)
    for x,z,s in [(-10.6,10.9,1.0),(-6.0,12.0,.8),(-9.4,21.6,.7),(5.3,11.0,.76),(5.2,20.8,.75),(-11.6,2.0,.85),(11.5,3.5,.7),(-13,28,.9),(-12,32,.8),(-9,34,.7),(3.5,29,.9)]:bush(g,x,z,s,rng)
    # Wood bench, tree supports and compact silver garden spotlights.
    for x,z in [(-10.5,15.0),(11.7,5.1)]:
        for j in range(5):g.box('garden_bench_slats',x,.46,z-.24+j*.115,1.9,.065,.096,'#766348',record=False)
        for dx in (-.66,.66):g.box('garden_bench_leg',x+dx,.23,z,.08,.46,.44,'#4e5750',True)
    for x,z in [(-9.7,17.4),(-3.9,16.1),(2.2,13.0),(4.4,18.8)]:
        g.box('garden_spot_base',x,.055,z,.30,.10,.26,'#575f5a',record=False)
        g.tube('garden_silver_spotlight',(x,.16,z),(x,.40,z-.20),.13,'#a2aca7',n=14)
        g.tube('garden_spot_glass',(x,.401,z-.20),(x,.412,z-.21),.108,'#d7dccb',n=14)
    # Three white cylinder planters beside the porch, seen in the frontal photograph.
    for i in range(3):
        x=2.5+i*.65;z=7.9
        g.vessel('garden_white_porch_pot',x,.02,z,.65,'#ddded4',profile=[(0,.27),(.80,.34),(.87,.35),(.87,.28),(.73,.28)])
        for j in range(6):
            a=j*math.tau/6;g.tube('porch_plant_stem',(x,.5,z),(x+math.cos(a)*.24,1.3-j*.05,z+math.sin(a)*.24),.012,'#777b48',n=5)
            g.rock('porch_plant_leaves',x+math.cos(a)*.27,1.25-j*.05,z+math.sin(a)*.27,.23,.08,.15,'#7f9155',rng)
    # Fine autumn grass blades keep the ground from reading as one flat rectangle.
    verts=[];faces=[]
    for i in range(5500):
        x=rng.uniform(-16,13);z=rng.uniform(-8,39)
        if not inside(x,z,boundary) or abs(x)<1.3 and z>7.5 or -9.4<x<9.4 and z<7 or -9<x< -3 and z<11:continue
        if inside(x,z,east) or inside(x,z,west):continue
        o=len(verts);h=rng.uniform(.04,.12);w=.016
        verts.extend([(x-w,.014,z),(x+w,.014,z),(x+rng.uniform(-.035,.035),h,z+.016)]);faces.append((o,o+1,o+2))
    g.mesh('garden_autumn_grass_tufts',verts,faces,'#8d8d58')
    g.label('타오르는 강 문학관',-1.65,1.12,9.28,1.0,.14,color='#e8e7d9')
    g.box('garden_visitor_information',-1.65,.94,9.20,1.15,1.7,.1,'#414b47',True)
    g.label('문학과 정원을\n함께 걷는 시간',-1.65,.73,9.27,.98,.16,color='#c9d2c4')
    # Paved approach bends towards the observed southwest garden entrance.
    approach=[[-6,37],[0,30],[0,24.5]]
    g.polygon('path_literature_garden',paved_outline(approach,2.25),.012,.040,'#8d9691')
    for a,b in zip(approach,approach[1:]):
        length=math.dist(a,b);dx=(b[0]-a[0])/length;dz=(b[1]-a[1])/length
        for j in range(int(length/.52)):
            x=a[0]+dx*(j+.5)*.52;z=a[1]+dz*(j+.5)*.52
            g.segment('garden_paver_joint',[x-dz*1.1,z+dx*1.1],[x+dz*1.1,z-dx*1.1],.02,.01,'#707e76',base=.053,record=False)
    # Short low side boundary and drainage channel; the south entrance stays open.
    for a,b in [([6.2,14],[6.2,35.8]),([-12.5,-8.5],[-12.5,11.5])]:
        g.segment('garden_neighbor_boundary',a,b,.20,.65,'#a5a69b',collision=True)
        g.segment('garden_boundary_coping',a,b,.27,.08,'#737d78',base=.65,record=False)
    for j in range(22):g.box('garden_lane_drain_grate',-15.0+j*.45,.036,38.3,.39,.025,.25,'#596b66',record=False)
    return dict(gate=[-6,37],route=[[-6,37],[0,30],[0,24.5],[0,17],[0,10],[0,7.2]],boundary=boundary)
